INSERT INTO emart.`USER`
(USERNAME, PASSWORD, `TYPE`, EMAIL, MOBILE, COMPANY, CREATE_DATE, ENABLED, LAST_PASSWORD_RESET_DATE)
VALUES('buyer1', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 0, '1', '1', '1', '2020-05-08', 1, '2020-05-08');

INSERT INTO emart.`USER`
(USERNAME, PASSWORD, `TYPE`, EMAIL, MOBILE, COMPANY, CREATE_DATE, ENABLED, LAST_PASSWORD_RESET_DATE)
VALUES('seller1', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 0, '1', '1', '1', '2020-05-08', 1, '2020-05-08');

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 2);