spring:
  application:
    name: seller-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emart?&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8098
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false